name: neon

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [maxos-14-latest]
        compiler: [ g++-14, clang++-15 ]

    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      working-directory: ${{github.workspace}}/Optimized_Implementation/neon
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/Optimized_Implementation/neon
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ./LESS_nist_cat_252_192
        ./LESS_nist_cat_252_68
        ./LESS_nist_cat_252_45
        ./LESS_nist_cat_400_220
        ./LESS_nist_cat_400_102
        ./LESS_nist_cat_548_345
        ./LESS_nist_cat_548_137
        sha1sum *.rsp
        tar -cf kats_avx2_${{matrix.os}}_${{matrix.compiler}}.tar *.rsp 
        ./LESS_benchmark_cat_252_192
        ./LESS_benchmark_cat_252_68
        ./LESS_benchmark_cat_252_45
        ./LESS_benchmark_cat_400_220
        ./LESS_benchmark_cat_400_102
        ./LESS_benchmark_cat_548_345
        ./LESS_benchmark_cat_548_137

    - name: save kats
      uses: actions/upload-artifact@v4
      with:
        name: kats_neon_${{matrix.os}}_${{matrix.compiler}}
        path: ${{github.workspace}}/build/kats_neon_${{matrix.os}}_${{matrix.compiler}}.tar
