name: ref

on: [push]
env:
  BUILD_TYPE: DEBUG

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-10, g++-11, g++-12, clang++-11, clang++-12, clang++-13, clang++-14, clang++-15, clang++-16 ]

    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Software
      run: |
        sudo apt-get install -y cmake libssl-dev
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/Reference_Implementation
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      working-directory: ${{github.workspace}}/Reference_Implementation
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ./LESS_nist_cat_1_BALANCED
        ./LESS_nist_cat_1_INTERMEDIATE
        ./LESS_nist_cat_1_SHORT_SIG
        ./LESS_nist_cat_3_BALANCED
        ./LESS_nist_cat_3_SHORT_SIG
        ./LESS_nist_cat_5_BALANCED
        ./LESS_nist_cat_5_SHORT_SIG
        ./LESS_test_cat_1_BALANCED
        ./LESS_test_cat_1_INTERMEDIATE
        ./LESS_test_cat_1_SHORT_SIG
        ./LESS_test_cat_3_BALANCED
        ./LESS_test_cat_3_SHORT_SIG
        ./LESS_test_cat_5_BALANCED
        ./LESS_test_cat_5_SHORT_SIG
        ./LESS_benchmark_cat_1_BALANCED
        ./LESS_benchmark_cat_1_INTERMEDIATE
        ./LESS_benchmark_cat_1_SHORT_SIG
        ./LESS_benchmark_cat_3_BALANCED
        ./LESS_benchmark_cat_3_SHORT_SIG
        ./LESS_benchmark_cat_5_BALANCED
        ./LESS_benchmark_cat_5_SHORT_SIG
